### ISSUE TITLE
URL shortner non va

### ISSUE THREAD

**Issue by hummusaki** [tommasobenatti/tommasobenatti#1]
Lo URL shortner rende lo URL piu' lungo

**Comment by tommasobenatti** [comment]
taci ebreo @Apoc101

**Comment by tommasobenatti** [comment]
ti prego rispondimi

**Comment by tommasobenatti** [comment]
così usiamo gli issue di github come chat real time

**Comment by tommasobenatti** [comment]
Comunque lo so, l'ho spento perché era su un server molto gay che puzzava di cazzo in putrefazione

**Comment by hummusaki** [comment]
ma poi non l'hai fatta te questa roba vero

**Comment by tommasobenatti** [comment]
no, l'ho skiddata

**Comment by hummusaki** [comment]
che strano

**Comment by hummusaki** [comment]
comunque guarda il sito di ghetti 

https://ghetti.online/

**Comment by hummusaki** [comment]
bi,bo cazzo
